# Generated by Django 6.0 on 2025-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(verbose_name='Lesson ID')),
                ('seq', models.IntegerField(verbose_name='Sequência')),
                ('role', models.CharField(max_length=30, verbose_name='Role')),
                ('auto', models.BooleanField(default=False, verbose_name='Auto')),
                ('end', models.BooleanField(default=False, verbose_name='End')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('status_point', models.BooleanField(default=False, verbose_name='Status Point')),
                ('lang', models.CharField(default='PT', max_length=2, verbose_name='Linguagem')),
                ('be_ready', models.BooleanField(default=False, verbose_name='Revisado')),
                ('content_pt', models.TextField(verbose_name='Conteúdo (PT)')),
                ('content_it', models.TextField(verbose_name='Conteúdo (IT)')),
                ('content_fr', models.TextField(verbose_name='Conteúdo (FR)')),
                ('content_es', models.TextField(verbose_name='Conteúdo (ES)')),
                ('expected_en', models.CharField(max_length=255, verbose_name='Expectativa (EN)')),
                ('expected_pt', models.CharField(max_length=255, verbose_name='Expectativa (PT)')),
                ('expected_it', models.CharField(max_length=255, verbose_name='Expectativa (IT)')),
                ('expected_fr', models.CharField(max_length=255, verbose_name='Expectativa (FR)')),
                ('expected_es', models.CharField(max_length=255, verbose_name='Expectativa (ES)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chats',
            },
        ),
    ]
