# Generated by Django 6.0 on 2025-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_create_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lang',
            field=models.CharField(choices=[('PT', 'Português'), ('EN', 'English'), ('IT', 'Italiano'), ('FR', 'Français'), ('ES', 'Español')], default='PT', max_length=2, verbose_name='Linguagem'),
        ),
    ]
