# Generated by Django 6.0 on 2025-12-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content_es',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo (ES)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo (FR)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content_it',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo (IT)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo (PT)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='expected_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expectativa (ES)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='expected_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expectativa (FR)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='expected_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expectativa (IT)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='expected_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expectativa (PT)'),
        ),
    ]
