# Generated by Django 6.0 on 2026-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_content_es_alter_chat_content_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='seq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequência'),
        ),
    ]
