# Generated by Django 6.0 on 2026-01-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alterar_seq_para_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['lesson_id', 'seq'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('points', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress',
                'indexes': [models.Index(fields=['user'], name='progress_user_id_c7d7f3_idx'), models.Index(fields=['lesson_id'], name='progress_lesson__b57b71_idx'), models.Index(fields=['chat'], name='progress_chat_id_ec888d_idx')],
            },
        ),
    ]
