# Generated by Django 6.0 on 2026-01-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_attempts_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='updated_at',
        ),
    ]
