# Generated by Django 6.0 on 2026-01-05 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='progress',
            name='progress_user_id_c7d7f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='progress',
            name='progress_chat_id_ec888d_idx',
        ),
        migrations.AddField(
            model_name='progress',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'chat'], name='progress_user_id_68377d_idx'),
        ),
    ]
