# Generated by Django 6.0 on 2026-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_create_user_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernivel',
            name='last_activation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernivel',
            name='last_password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
