# Generated by Django 6.0 on 2026-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_usernivel_last_activation_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernivel',
            name='earned_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usernivel',
            name='spent_credit',
            field=models.IntegerField(default=0),
        ),
    ]
